language: cpp
os: linux
sudo: required
compiler: gcc
dist: bionic

packages:
  - cmake

before_script:
  - sudo apt update && sudo apt -y install libboost-all-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make