language: cpp
os: linux
sudo: required
compiler: gcc
dist: trusty

packages:
  - cmake
  - g++-7.4

before_script:
  - apt update && apt -y install libboost-all-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./unit_test
